### ISSUE TITLE
Send out awesome_digest style emails daily.

### ISSUE THREAD

**Issue by mathias** [mathias/gnar#1]
This could be added with a cron job and a Clojure script that runs against the same database as this app; it doesn't need to be part of the web process. Or it could be. Up to the person who implements this.

**Comment by losingkeys** [comment]
I'm not sure how html vs text emails work, but in mutt I think it'll show just the text version if available, so we should make sure text-based emails work too.

Also, the old awesome emails that get sent out do send just text... but it look like this:

```
http://blah/?something=something\r\nhttp://other.blah/whatever\r\nhttp://lol.try.to.click.these/blah
```

Which is hard to read/click
