### ISSUE TITLE
handle normal form submission

### ISSUE THREAD

**Issue by losingkeys** [mathias/gnar#5]
When registering, hitting enter seems to make the user, but doesn't either log in or switch back to the login form.

Also: should the search be hidden when registering (just more stuff on the page)?

**Comment by mathias** [comment]
We'll need to look into whether we're catching all form submission events
or just button presses for the form. Should be doing both, for all forms.

On Mon, Mar 24, 2014 at 1:33 PM, Joshua Hoff notifications@github.comwrote:

> When registering, hitting enter seems to make the user, but doesn't either
> log in or switch back to the login form.
> 
> Also: should the search be hidden when registering (just more stuff on the
> page)?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/mathias/gnar/issues/5
> .

## 

Matt Gauger
http://blog.mattgauger.com
