### ISSUE TITLE
Hide the "add new link" form by default?

### ISSUE THREAD

**Issue by losingkeys** [mathias/gnar#6]
After you add a link it shows up right underneath the form, which is pretty cool. However the form sticks around taking up space when you might want to just scroll through the links. I think it'd be cool to either:
- hide the form (maybe a + button somewhere to toggle it)
- clear the form (so you can add another link)

**Comment by mathias** [comment]
The plan is to have the forms toggle show/hide in the header bar. And which things you can toggle to show/hide with a button will be based on whether you're logged in or not.

Here's a terrible sketch of what I'm thinking for the logged-out versions:

![skitched-20140324-113939](https://f.cloud.github.com/assets/3340/2503571/b09add4c-b383-11e3-8144-dd8d60fbc4cf.png)

With a similar set of buttons for "Add a link" showing when you are logged in.
